### ISSUE TITLE
Build envorinment

### ISSUE THREAD

**Issue by jbschooley** [wingspinner/HooToo-Tripmate-HT-TM02-OpenWRT#15]
May I ask what your build environment is? I want to use a mt7601u wifi stick with my TM02, but the trunk build bricked my device and I had to send it in for a replacement. I think the next best thing to do is to build an image myself with the newer kernel version that supports it, but I have no idea how to do it, and I won't be able to get another replacement if I brick this one.

**Comment by wingspinner** [comment]
I’m surprised they will provide a replacement due to users trying to load other than factory firmware. Anyhow, I used exactly the environment from the OpenWRT website for Debian Linux. There is no such thing as bricking one of these things they are always recoverable. If you are building the trunk build it’s nearly always a network configuration issue. If you dont know how to get into it then use the boot monitor to load a new build that has a valid network configuration. Had to do that plenty of times while I was learning about them. Plenty of instructions from the Openwrt and other forums. 

Best of luck!

**Comment by jbschooley** [comment]
What do you mean by the boot monitor? Is that a piece of software that I can get off the OpenWrt forums somewhere, and do I have to get a serial adapter to use it?

I am 100% certain it was a network config issue but I don't have a serial adapter or any knowledge on how to use one.
