### ISSUE TITLE
Building an openwrt factory image

### ISSUE THREAD

**Issue by ianclegg** [wingspinner/HooToo-Tripmate-HT-TM02-OpenWRT#6]
Hi Ron,

Thanks for sharing your findings; its clear you put a lot of time and effort it in - and its saved a lot of other engineers and hackers a lot of time.
I'm trying to build a factory image for another device; with identical hardware to the HooToo. Its the RAVPower RP-WD01. It does not have an Ethernet port, so I need to flash it and have Wireless work straight away.

I can do this I can build a 'factory' image with a sysupgrade image with wireless ready to go. I have a HooToo TM02 to practice on. I have pulled revision r42649 and applied your patch; I have baked in a wireless config.
You mentioned in your posts on openwrt forums:

"Factory firmware update mechanism is not compatible with standard OpenWRT images. I’ve decoded the factory image format..."

"This is the "factory" upgrade image to be used by the factory HooToo software to do the initial upgrade to OpenWRT.It is based on the same binary image as the normal OpenWRT sysupgrade image but has been re-packaged with a loader, CRC, etc. such that the factory HooToo software will accept it. The factory HooToo software is filename sensitive and will reject the file if it's too different from what it expects. If the TM02 rejects this name try changing it to "fw-WiFiPort-HooToo-TM02-2.000.018"

Can you offer any direction on how to develop the loader and the CRC required, also the filename check?

Thanks
Ian

**Comment by wingspinner** [comment]
The HooToo uses a structure that's very different than most. It has binary images embedded with a shell script that's very specific to the HooToo Linux configuration. I'm 100% sure it's totally incompatible with anything else. I deduced all this with a hex editor and taking a standard HooToo image apart and analyzing what it all does. Then I wrote a new script and after a bunch of hours debugging got it to work. I would start by getting the hexeditor out and looking at the RAVPower images. For a one off, it's not worth all the work in my opinion. I recommend finding the serial port connections and getting into both it's uboot (if it uses that) and also the Linux console. Nearly every embedded Linux I've ever looked at already has the software tools on-board to reprogram the FLASH with a new Linux image - get into the console and find those and you'll be set.

Cheers,
Ron

**Comment by ianclegg** [comment]
Hi Ron,
Thanks for the tip; I didn't want to jam a screwdriver into it just yet. I dug around in a hex editor and took a look. Sure enough, its a shell script stub which checks the CRC, performs a backup, quiesces the system and then starts the flash:

CRCSUM=1244231419
OEM=POWER7
VERSION=2000030
VENDOR=RAV
PRODUCTLINE=SD
SKIP=173
TARGET_OS="linux"
TARGET_ARCH="arm"
DEVICE_TYPE=WD01
CPU=5350

Once I got the CRC at the start figured out it just worked!!...

I have since added SDHCI support, then cloned and build an exfat kernel driver based on Yuri's driver over at https://github.com/dorimanx - it'll mount and r/w 64GB SD Cards. Now I can finally backup my DSLR photos to USB on the move. I'm still sorting out the LED's, but I'll write this up and share the scripts later in the week.

Thanks for the tip
Ian

**Comment by wingspinner** [comment]
Hi Ian,
Well, that’s a first for me! I haven’t seen any other 5350 based devices using a shell script like these do. Sounds like they may be using the same software contractor since it’s very similarl. I am looking at writing a “make image” tool to automatically make these “factory” images as part of the OpenWRT builder but at the moment my time is consumed with higher priority stuff (like looking for a new job). I do have a shell script though that does the job. I don’t mind sharing it. It’s attached. It’s under the “Open Commons” license so please share any progress you make with it.

Btw, I just got a TM04 which is really an awesome unit and it has an SD card, a built-in battery, etc and there is a sticker inside that says RAVxxxx so I’m thinking that your unit and the TM04 may be made by the same company.

Cheers,
Ron

**Comment by wingspinner** [comment]
Ian,

A follow-up question in addition to my previous reply…

Isn’t there already a exFAT and VFAT kernel driver? I’m curious as to why you didn’t use that. As well, on the SDHCI support did you use the OpenWRT kernel driver or is this something you developed on your own?

Lastly, I’m curious about what you did with the loader script. I found a few things, first, the existing UBoot partition isn’t compatible with OpenWRT (at least if you don’t want to sacrifice a substantial amount of the FLASH. As well, I found that I had rewrite the secondary script for various reasons. Are you saying you just plopped in a sys upgrade image into the HooToo image, changed the CRCSUM and off it went or that you started with my factory image.

Just curious and interested.

Thanks for the note!

Cheers,
Ron

**Comment by ianclegg** [comment]
Hey Ron,

openwrt trunk has kernel mode drivers for ntfs and vfat, but not exfat. I'm pretty sure there is a user land fuse based driver, but I didn't fancy the performance hit on a device like this if a kernel mode implementation is available elsewhere. Patching it into openwrt only took half an hour - yuri's driver is based on the GPL'd samsung code. I ran an overnight read/write test and got a sustained 4.7MB/sec transfer rate from SD to USB - comparable with Tuxera's driver which ships with the RAVPower.

It wasn't as straight forward as fixing up the crc and replacing HooToo's image; but not too far off. I didn't know there were any issues with uBoot and openwrt - so the quickest thing for me to try was writing the openwrt sysupgrade image into the firmware partition starting at 0x50000 - just as you might normally do. Since the mtd tool on the device doesn't seem to be able to target an offset - the simplest approach was to write out the first 3 partitions and concatenate them with my sysupgrade image - then write the whole lot back.

[    0.490000] 0x000000000000-0x000000030000 : "u-boot"
[    0.500000] 0x000000030000-0x000000040000 : "u-boot-env"
[    0.520000] 0x000000040000-0x000000050000 : "factory"
[    0.520000] 0x000000050000-0x000000800000 : "firmware"
[    0.550000] 0x000000150430-0x000000800000 : "rootfs"

cross you fingers, wait... wait.. and it booted :+1: 

You mentioned wasting flash: so are all of those first 3 partitions needed? I assume your approach did away with them?

**Comment by wingspinner** [comment]
Ah, got it. I’d love to get hold of your exfat driver!

On the the upgrade. There are no issues with OpenWRT and uboot. However, every uboot has the MTD partitioning hard-coded into it and the HooToo devices use a modified version with different partitioning. It so happens that their kernel image partition is at 0x50000 but it’s a very short partition because after that is a “parameters” partition, then another partition, THEN the rootFS. It’s kind of messed up for OpenWRT purposes.  RAVPower may not be using the same hacked up UBoot that HooToo is though. 

However, the listing you show appears to be the Linux boot kernel messages and that will always show the partitioning Linux is using which isn’t necessarily the same as what the firmware is using. In fact, unless you pass some partitioning info in the boot command line Linux/OpenWRT will pretty much ignore uboot partitioning. As long as you aren’t overwriting the “factory” partition” n some ways it’s a don’t care. Where it can be a problem is if you try to upgrade the kernel image via TFTP. In the case of the TM02 the kernel (firmware) partition is quite small because they separated the rootFS from it and that partition is only big enough for the bare kernel. HooToo uboot  will reject an OpenWRT sys upgrade image more often than not for that reason. 

You may know this but you have a unit that still has the stock firmware you can find out what partitioning it uses via “cat mtd” in the proc directory.

In anyway, what you did is pretty much how I got OpenWRT on the TM02 the first time except I swapped out the uboot and used TFTP. 

On another note, it appears that the RAVPower device and the TM04 may be the same unit or at least very similar. I just got one a couple of days ago and when I removed the RF shielding I found a sticker labeled “RAV-XXXXX” inside the daughter-card module. I found the my factory images and the trunk image  work without modification on it. That’s good news because it’s a very nice little unit with built-in 3000mah battery and both SD and USB ports for only $29. 

In any case, I think I mentioned that I released my factory image builder tool on my GitHub repository. You may be able to use that in the future if you buy more devices. It generates HooToo compatible firmware upgrade images and replaces the uboot with one that has identical partitioning to OpenWRT as well as installing OpenWRT.

Thanks for the interesting discussion!

Best,
Ron

**Comment by ianclegg** [comment]
I'll put together an exfat patch - it didn't need code changes, just the right makefiles to build. Regarding the flash partitions, did your loader blow away the the 'u-boot-env' and 'factory' partitions?

**Comment by ianclegg** [comment]
One last thing about exfat (and ntfs for that matter) - they are not automounted on openwrt. I looked into this and it looks like the project moved over to using ubox for hotplug automouting; this in turn uses a custom version of libblkid (called libblkid-tiny) that probes the device and uses a set of heuristics to establish the file system. The logic for exfat and ntfs are not present - but again it looks pretty straight forward to add. The full fat version of libblkid has them. I'll prod it a bit and see what happens

**Comment by ianclegg** [comment]
I missed the last paragraph of your last post, yer I was being lazy and posted the linux boot messages - so it looks like I was lucky with the flashing. Thanks for the tips!

**Comment by wingspinner** [comment]
No, it retains those. My loader installs a new uboot with the correct OpenWRT partitioning along with a sysupgrade image while retaining those partitions that are required. It also writes out a full backup of the original firmware to a USB Flash stick in case you ever want to go back. The u-boot-env partition is required by uboot and the factory partition contains parameters and calibration info for the wifi chip. If that get’s blown away there’s a good chance the wifi won’t work very well or not work at all. Or so RALink tells me. I’ve not actually done it to test it ;-) . 

Cheers,
Ron
